name: Build Android App
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - run: .flutter/bin/flutter pub get
    #- run: flutter test
    - run: .flutter/bin/flutter build apk --debug --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: apk-debug
        path: build/app/outputs/apk/debug/app-debug.apk
    - name: Create Release
      id: create_release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ github.ref }}
        prerelease: false
        files: |
          build/app/outputs/apk/debug/app-debug.apk
